<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PythagoricMeaningsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $rows = [
            // ---------- PERCORSO DI VITA 1–9 life_path ---------- //
            [
                'number_type'       => 'life_path',
                'number_value'      => 1,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 1 – Il Pioniere',
                'short_description' => 'Indipendenza, leadership, iniziativa personale.',
                'long_description'  => 'Il percorso di vita 1 indica una persona nata per guidare, aprire strade e prendere decisioni in autonomia. La sfida principale è imparare a collaborare senza perdere la propria identità e senza cadere nell’ego o nell’isolamento.',
                'metadata'          => json_encode([
                    'keywords' => ['leadership', 'indipendenza', 'iniziativa'],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'life_path',
                'number_value'      => 2,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 2 – Il Mediatore',
                'short_description' => 'Cooperazione, sensibilità, diplomazia.',
                'long_description'  => 'Il percorso di vita 2 è legato all’arte della relazione, dell’ascolto e della cooperazione. La persona è chiamata a creare armonia e collaborazione, imparando però a non annullarsi per compiacere gli altri.',
                'metadata'          => json_encode([
                    'keywords' => ['cooperazione', 'sensibilità', 'diplomazia'],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'life_path',
                'number_value'      => 3,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 3 – Il Creativo',
                'short_description' => 'Espressione, comunicazione, creatività.',
                'long_description'  => 'Il percorso di vita 3 porta con sé energia creativa, talento comunicativo e bisogno di esprimere emozioni e idee. La lezione principale riguarda la disciplina e la capacità di concretizzare i propri doni.',
                'metadata'          => json_encode([
                    'keywords' => ['creatività', 'espressione', 'comunicazione'],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'life_path',
                'number_value'      => 4,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 4 – Il Costruttore',
                'short_description' => 'Stabilità, ordine, lavoro concreto.',
                'long_description'  => 'Il percorso di vita 4 è legato alla costruzione solida: disciplina, organizzazione, responsabilità. La sfida è evitare rigidità eccessiva e aprirsi a nuove soluzioni senza perdere struttura.',
                'metadata'          => json_encode([
                    'keywords' => ['stabilità', 'disciplina', 'lavoro'],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'life_path',
                'number_value'      => 5,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 5 – Il Viaggiatore',
                'short_description' => 'Libertà, cambiamento, esperienza.',
                'long_description'  => 'Il percorso di vita 5 porta continuo movimento, desiderio di libertà e ricerca di esperienze. La lezione principale è imparare a gestire la libertà con responsabilità, evitando eccessi e dispersione.',
                'metadata'          => json_encode([
                    'keywords' => ['libertà', 'cambiamento', 'avventura'],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'life_path',
                'number_value'      => 6,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 6 – Il Custode',
                'short_description' => 'Responsabilità, famiglia, servizio.',
                'long_description'  => 'Il percorso di vita 6 richiama alla cura degli altri, alla famiglia, alla bellezza e all’armonia. La difficoltà è non cadere nel controllo e nel sacrificio eccessivo, mantenendo un sano equilibrio tra dare e ricevere.',
                'metadata'          => json_encode([
                    'keywords' => ['famiglia', 'cura', 'servizio'],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'life_path',
                'number_value'      => 7,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 7 – Il Ricercatore',
                'short_description' => 'Introspezione, spiritualità, analisi.',
                'long_description'  => 'Il percorso di vita 7 è associato alla ricerca interiore, allo studio, alla spiritualità e alla profondità. La sfida è non isolarsi e imparare a condividere ciò che si scopre con il mondo.',
                'metadata'          => json_encode([
                    'keywords' => ['spiritualità', 'analisi', 'introspezione'],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'life_path',
                'number_value'      => 8,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 8 – Il Realizzatore',
                'short_description' => 'Potere, successo materiale, responsabilità.',
                'long_description'  => 'Il percorso di vita 8 riguarda la gestione del potere, del denaro e della realizzazione concreta. La lezione è usare l’energia del successo in modo etico, equilibrando ambizione e integrità.',
                'metadata'          => json_encode([
                    'keywords' => ['potere', 'successo', 'responsabilità'],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'life_path',
                'number_value'      => 9,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 9 – Il Donatore',
                'short_description' => 'Compassione, servizio universale, chiusura di cicli.',
                'long_description'  => 'Il percorso di vita 9 richiama alla compassione, all’umanitarismo e alla chiusura dei cicli karmici. La sfida è lasciare andare il passato e donare senza perdere se stessi.',
                'metadata'          => json_encode([
                    'keywords' => ['compassione', 'umanitarismo', 'chiusura'],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- PERCORSO DI VITA 11–22-33 life_path (numeri maestri) ---------- //
            [
                'number_type'       => 'life_path',
                'number_value'      => 11,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 11 - Il Messaggero spirituale',
                'short_description' => 'Intuizione elevata, ispirazione e chiamata interiore.',
                'long_description'  => 'Il percorso di vita 11 è quello dell’anima ispirata. Fin dall’inizio della vita puoi percepire una sensibilità fuori dal comune, un’intuizione profonda e una tensione verso il senso ultimo delle cose. Sei chiamato a fare da ponte tra visibile e invisibile, tra conferma e mistero. La sfida è imparare a radicare la tua visione per non viverla come peso o instabilità.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'intuizione',
                        'ispirazione',
                        'canale spirituale',
                        'visione elevata',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'life_path',
                'number_value'      => 22,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 22 - Il Maestro costruttore',
                'short_description' => 'Visione ampia e capacità di realizzare opere durature.',
                'long_description'  => 'Il percorso di vita 22 unisce il sogno alla materia. Sei chiamato a costruire qualcosa che resti: progetti, strutture, sistemi o comunità. Hai la capacità di tradurre un’idea elevata in una forma concreta. La prova è non farti schiacciare dal peso delle responsabilità e ricordare che ogni costruzione autentica nasce da un senso profondo.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'realizzazione',
                        'costruzione',
                        'visione incarnata',
                        'opera duratura',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'life_path',
                'number_value'      => 33,
                'locale'            => 'it-IT',
                'title'             => 'Percorso di vita 33 - Il Maestro dell’amore',
                'short_description' => 'Vocazione al servizio, alla compassione e alla guarigione.',
                'long_description'  => 'Il percorso di vita 33 è il più raro e intenso. Porta una chiamata al servizio disinteressato, all’insegnamento e alla guarigione attraverso l’amore. Spesso comporta grandi prove emotive, perché l’anima impara ad amare senza condizioni. La sfida è non sacrificarsi fino all’annullamento, ma incarnare la compassione restando integri.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'amore universale',
                        'servizio',
                        'guarigione',
                        'insegnamento spirituale',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- EXPRESSION 1–9 (talenti e potenziale espresso) ---------- //
            [
                'number_type'       => 'expression',
                'number_value'      => 1,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 1 - Il Comandante',
                'short_description' => 'Talento nel dirigere, decidere e guidare.',
                'long_description'  => 'Con un numero di espressione 1, la tua personalità manifesta coraggio, iniziativa e bisogno di guidare. Sei portato a prendere il comando, ad avviare progetti, a proporre soluzioni. Puoi risultare diretto o impaziente, ma la tua forza sta nella chiarezza di visione. Quando usi il tuo potere in modo costruttivo, ispiri gli altri ad alzarsi in piedi e seguire il proprio cammino.',
                'metadata'          => json_encode(['keywords' => ['leadership', 'decisione', 'autonomia']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'expression',
                'number_value'      => 2,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 2 - Il Collaboratore',
                'short_description' => 'Talento nella cooperazione, nell’ascolto e nella mediazione.',
                'long_description'  => 'L’espressione 2 ti dona una presenza gentile, diplomatica, sensibile alle vibrazioni degli altri. Spicchi quando puoi cooperare, sostenere, facilitare accordi. Potresti avere difficoltà a esprimere apertamente i tuoi bisogni, temendo il conflitto. Quando ti permetti di parlare con sincerità, diventi un vero punto di riferimento per chi cerca equilibrio e armonia.',
                'metadata'          => json_encode(['keywords' => ['collaborazione', 'diplomazia', 'sensibilità']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'expression',
                'number_value'      => 3,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 3 - Il Narratore',
                'short_description' => 'Talento verbo-creativo, comunicazione brillante.',
                'long_description'  => 'Con l’espressione 3, porti nel mondo leggerezza, humour e capacità di raccontare. Sai usare parole, immagini e gesti per trasmettere emozioni e idee. Puoi però fuggire dalle profondità emotive, mascherando la vulnerabilità con la battuta. Quando ti permetti di parlare anche del dolore, la tua arte diventa medicina per chi ti ascolta.',
                'metadata'          => json_encode(['keywords' => ['narrazione', 'arte', 'comunicazione']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'expression',
                'number_value'      => 4,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 4 - L’Organizzatore',
                'short_description' => 'Talento pratico, metodo e affidabilità.',
                'long_description'  => 'L’espressione 4 ti rende concreto, sistematico e affidabile. Pensi in termini di processi, strutture e risultati tangibili. Gli altri possono contare su di te, ma talvolta ti percepiscono rigido o troppo razionale. Quando integri la flessibilità e lasci entrare un po’ di creatività nel tuo ordine, diventi un costruttore straordinario di progetti duraturi.',
                'metadata'          => json_encode(['keywords' => ['organizzazione', 'pragmatismo', 'metodo']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'expression',
                'number_value'      => 5,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 5 - L’Esploratore',
                'short_description' => 'Talento per il cambiamento, la varietà e la comunicazione dinamica.',
                'long_description'  => 'Con un numero di espressione 5, porti entusiasmo, curiosità e spirito avventuroso. Sei a tuo agio con il nuovo, ami sperimentare, cambiare, raccontare ciò che vivi. Il rischio è la dispersione o la tendenza ad annoiarti facilmente. Quando impari a canalizzare questa energia in progetti chiari, diventi un comunicatore magnetico e un ponte tra mondi diversi.',
                'metadata'          => json_encode(['keywords' => ['avventura', 'varietà', 'movimento']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'expression',
                'number_value'      => 6,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 6 - Il Protettore',
                'short_description' => 'Talento nel prendersi cura, educare e armonizzare.',
                'long_description'  => 'L’espressione 6 ti rende naturalmente portato a proteggere, consigliare, sostenere. Hai senso estetico, amore per la casa, per la bellezza e per le relazioni affettive. Puoi però cadere nel controllo o nell’iper-responsabilità. Quando ti prendi cura senza sostituirti agli altri, diventi un punto fermo di stabilità e amore nel tuo ambiente.',
                'metadata'          => json_encode(['keywords' => ['cura', 'armonia', 'famiglia']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'expression',
                'number_value'      => 7,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 7 - Il Saggio',
                'short_description' => 'Talento analitico, intuitivo e contemplativo.',
                'long_description'  => 'Con l’espressione 7, trasmetti profondità, riservatezza e uno sguardo indagatore. Ami capire, studiare, contemplare. A volte puoi sembrare distante o enigmatico. Quando condividi con semplicità ciò che scopri dentro di te e nel mondo, diventi una guida preziosa per chi cerca risposte autentiche.',
                'metadata'          => json_encode(['keywords' => ['saggezza', 'analisi', 'intuizione']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'expression',
                'number_value'      => 8,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 8 - Il Manager',
                'short_description' => 'Talento nella gestione di risorse, persone e obiettivi.',
                'long_description'  => 'L’espressione 8 dona presenza, ambizione e capacità di gestione. Sai organizzare strutture, guidare team, muoverti in contesti dove contano risultati e responsabilità. Puoi però diventare troppo severo, competitivo o orientato solo ai numeri. Quando unisci cuore e strategia, diventi un leader giusto e rispettato.',
                'metadata'          => json_encode(['keywords' => ['gestione', 'autorità', 'strategia']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'expression',
                'number_value'      => 9,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 9 - Il Visionario',
                'short_description' => 'Talento umanitario, artistico e universale.',
                'long_description'  => 'Con il numero di espressione 9, emani sensibilità, idealismo e profondità emotiva. Spesso sei attratto dall’arte, dalla cura, dal volontariato o da progetti di ampio respiro. Puoi soffrire molto per le ingiustizie e sentirti disilluso. Quando impari a trasformare il dolore in servizio creativo, diventi un faro per chi cerca speranza.',
                'metadata'          => json_encode(['keywords' => ['visione', 'umanitarismo', 'arte']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- EXPRESSION 11–22-33 (numeri maestri - talenti e potenziale espresso) ---------- //
            [
                'number_type'       => 'expression',
                'number_value'      => 11,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 11 - Il Canale ispirato',
                'short_description' => 'Talento ispirativo, comunicazione intuitiva e visione elevata.',
                'long_description'  => 'Con un’espressione 11, manifesti un carisma sottile e magnetico. Le tue parole, le tue idee e la tua presenza possono risvegliare, ispirare o guidare gli altri. Non sempre è facile “incassare” questa sensibilità: il rischio è l’ansia o la dispersione. Quando radichi l’intuizione nella pratica quotidiana, la tua espressione diventa faro.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'ispirazione',
                        'intuizione',
                        'comunicazione elevata',
                        'carisma sottile',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'expression',
                'number_value'      => 22,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 22 - Il Realizzatore visionario',
                'short_description' => 'Talento nel trasformare grandi idee in risultati concreti.',
                'long_description'  => 'L’espressione 22 unisce mente visionaria e capacità organizzativa. Sai progettare, strutturare e guidare iniziative complesse. La tua comunicazione è autorevole e orientata allo scopo. La sfida è non diventare rigido o eccessivamente focalizzato sul risultato, dimenticando il senso più alto dell’opera.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'realizzazione',
                        'visione pratica',
                        'leadership strutturata',
                        'costruzione',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'expression',
                'number_value'      => 33,
                'locale'            => 'it-IT',
                'title'             => 'Espressione 33 - Il Comunicatore compassionevole',
                'short_description' => 'Talento nell’insegnare, guarire e sostenere attraverso la parola.',
                'long_description'  => 'Con un’espressione 33, ciò che manifesti nel mondo ha una forte impronta di amore e servizio. La tua voce, il tuo esempio o il tuo lavoro parlano di cura, empatia e responsabilità verso gli altri. Il rischio è sovra-donarti. La vera maestria è esprimere compassione restando centrato.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'insegnamento',
                        'compassione',
                        'guarigione',
                        'servizio espresso',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- SOUL URGE 1–9 (desideri interiori) ---------- //
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 1,
                'locale'            => 'it-IT',
                'title'             => 'Anima 1 – Desiderio di autonomia',
                'short_description' => 'Bisogno profondo di essere indipendente e unico.',
                'long_description'  => 'Con un numero dell’anima 1, dentro di te c’è il desiderio ardente di essere te stesso senza compromessi. Non sopporti di essere controllato o sminuito. A livello più profondo, cerchi situazioni in cui poter decidere, creare, dirigere la tua vita. La sfida è non confondere libertà con isolamento: il cuore vuole autonomia, ma non solitudine.',
                'metadata'          => json_encode(['keywords' => ['autonomia', 'unicità', 'libertà interiore']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 2,
                'locale'            => 'it-IT',
                'title'             => 'Anima 2 – Desiderio di unione',
                'short_description' => 'Bisogno profondo di connessione, dolcezza e cooperazione.',
                'long_description'  => 'L’anima 2 cerca comprensione, sostegno e rapporti armoniosi. In profondità desideri sentirti accolto, ascoltato e accompagnato. Le ferite arrivano quando ti senti escluso o non considerato. Imparare a esprimere ciò che senti, senza aspettare che l’altro lo indovini, è un passo essenziale per la tua pace interiore.',
                'metadata'          => json_encode(['keywords' => ['unione', 'tenerezza', 'alleanza']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 3,
                'locale'            => 'it-IT',
                'title'             => 'Anima 3 – Desiderio di esprimersi',
                'short_description' => 'Bisogno profondo di creatività, gioco e condivisione.',
                'long_description'  => 'Con l’anima 3, dentro di te vive un bambino creativo che vuole ridere, creare, raccontare e condividere emozioni. Soffri quando devi reprimere ciò che provi o quando l’ambiente è troppo rigido. Il cuore desidera spazi di libertà artistica e relazioni in cui puoi parlare senza sentirti giudicato.',
                'metadata'          => json_encode(['keywords' => ['espressione', 'gioco', 'creatività interiore']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 4,
                'locale'            => 'it-IT',
                'title'             => 'Anima 4 – Desiderio di sicurezza',
                'short_description' => 'Bisogno profondo di stabilità, ordine e affidabilità.',
                'long_description'  => 'L’anima 4 desidera sentirsi al sicuro, con punti fermi, routine sane e certezze. Dentro di te c’è la richiesta di chiarezza: sapere dove stai andando, con chi e perché. La destabilizzazione, il caos o i cambiamenti improvvisi ti feriscono. Imparare a creare sicurezza anche dentro di te, non solo fuori, ti dona grande forza.',
                'metadata'          => json_encode(['keywords' => ['sicurezza', 'ordine', 'solidità interiore']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 5,
                'locale'            => 'it-IT',
                'title'             => 'Anima 5 – Desiderio di libertà',
                'short_description' => 'Bisogno profondo di movimento, esperienza e novità.',
                'long_description'  => 'Con l’anima 5, una parte di te ha bisogno di respirare, cambiare, sperimentare. Situazioni troppo strette, monotone o controllanti prosciugano la tua energia. Il cuore vuole avventura, ma anche verità: relazioni e progetti in cui puoi essere autentico, senza catene invisibili.',
                'metadata'          => json_encode(['keywords' => ['libertà', 'esperienza', 'novità']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 6,
                'locale'            => 'it-IT',
                'title'             => 'Anima 6 – Desiderio di amore e armonia',
                'short_description' => 'Bisogno profondo di legami affettivi sinceri e stabili.',
                'long_description'  => 'L’anima 6 cerca amore, bellezza e armonia familiare. In profondità desideri relazioni sincere, casa accogliente, cura reciproca. Le ferite nascono quando ti senti dato per scontato o quando ti carichi di ruoli che non ti appartengono. Il cuore guarisce quando impari a ricevere tanto quanto dai.',
                'metadata'          => json_encode(['keywords' => ['amore', 'famiglia', 'armonia affettiva']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 7,
                'locale'            => 'it-IT',
                'title'             => 'Anima 7 – Desiderio di verità',
                'short_description' => 'Bisogno profondo di senso, silenzio e autenticità spirituale.',
                'long_description'  => 'Con l’anima 7, una parte di te anela alla verità, alla purezza d’intenti, alla profondità spirituale. Superficialità e falsità ti feriscono più di quanto mostri. Il cuore cerca momenti di silenzio, studio, contemplazione, ma anche relazioni in cui puoi parlare di ciò che senti davanti a Dio e davanti alla vita.',
                'metadata'          => json_encode(['keywords' => ['verità', 'spiritualità', 'autenticità']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 8,
                'locale'            => 'it-IT',
                'title'             => 'Anima 8 – Desiderio di impatto',
                'short_description' => 'Bisogno profondo di realizzare, incidere, lasciare un segno.',
                'long_description'  => 'L’anima 8 vuole sentire che la propria vita conta davvero. Dentro di te c’è il desiderio di raggiungere obiettivi importanti, di usare bene i talenti, di gestire risorse e opportunità. Ti senti frustrato quando ti percepisci impotente o bloccato. La pace interiore arriva quando unisci successo e valori, potere e coscienza.',
                'metadata'          => json_encode(['keywords' => ['impatto', 'realizzazione', 'missione concreta']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 9,
                'locale'            => 'it-IT',
                'title'             => 'Anima 9 – Desiderio di donare',
                'short_description' => 'Bisogno profondo di aiutare, guarire, restituire al mondo.',
                'long_description'  => 'Con l’anima 9, il cuore desidera essere utile agli altri, trasformare il dolore in amore, chiudere cicli in modo saggio. Puoi sentire forte l’ingiustizia e il bisogno di portare sollievo dove c’è sofferenza. Il rischio è sacrificarti troppo o trattenere relazioni ormai finite. La vera pace arriva quando doni senza annullarti.',
                'metadata'          => json_encode(['keywords' => ['donare', 'guarigione', 'servizio universale']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- SOUL URGE 11-22-33 (numeri maestri - desideri interiori) ---------- //
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 11,
                'locale'            => 'it-IT',
                'title'             => 'Anima 11 – Desiderio di luce e verità',
                'short_description' => 'Bisogno profondo di senso, ispirazione e connessione spirituale.',
                'long_description'  => 'Con un’anima 11, nel profondo senti il richiamo alla verità, alla bellezza nascosta e a una realtà più grande. Desideri comprendere il senso delle cose e vivere in coerenza con una visione interiore elevata. Puoi sentire inquietudine se vivi solo nella materia. Il cuore trova pace quando onori l’intuizione senza fuggire dal mondo.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'ricerca interiore',
                        'verità',
                        'intuizione profonda',
                        'luce spirituale',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 22,
                'locale'            => 'it-IT',
                'title'             => 'Anima 22 – Desiderio di costruire qualcosa che resti',
                'short_description' => 'Bisogno profondo di rendere utile e concreta la propria visione.',
                'long_description'  => 'L’anima 22 desidera lasciare un segno tangibile nel mondo. Dentro di te c’è il bisogno di creare, strutturare e realizzare qualcosa che abbia valore duraturo. Non ti basta sognare: vuoi incarnare. La frustrazione nasce quando non vedi risultati concreti. La pace arriva quando riconosci che ogni opera grande cresce passo dopo passo.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'costruzione interiore',
                        'realizzazione',
                        'visione concreta',
                        'responsabilità profonda',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'soul_urge',
                'number_value'      => 33,
                'locale'            => 'it-IT',
                'title'             => 'Anima 33 – Desiderio di amare e servire',
                'short_description' => 'Bisogno profondo di donarsi, guarire e sostenere gli altri.',
                'long_description'  => 'Con un’anima 33, nel profondo desideri amare senza condizioni. Il cuore è naturalmente orientato al servizio, alla cura e alla guarigione. Spesso senti il dolore altrui come fosse tuo. La lezione è imparare a servire senza annullarti, riconoscendo che anche tu meriti amore e sostegno.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'amore universale',
                        'servizio',
                        'guarigione',
                        'compassione interiore',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- PERSONALITY 1–9 (immagine esterna) ---------- //
            [
                'number_type'       => 'personality',
                'number_value'      => 1,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 1 – Presenza decisa',
                'short_description' => 'Appari diretto, forte, orientato all’azione.',
                'long_description'  => 'Con una personalità 1, gli altri ti percepiscono come una persona determinata, che sa cosa vuole. Puoi sembrare competitivo, orgoglioso o poco incline a chiedere aiuto. In realtà porti una forza naturale che, se addolcita dall’ascolto, diventa esempio di coraggio per chi ti circonda.',
                'metadata'          => json_encode(['keywords' => ['decisione', 'forza', 'iniziativa esterna']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'personality',
                'number_value'      => 2,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 2 – Presenza delicata',
                'short_description' => 'Appari gentile, discreto e accomodante.',
                'long_description'  => 'La personalità 2 ti rende visibile come persona educata, disponibile e sensibile. Gli altri ti vedono come qualcuno che non ama lo scontro e che cerca sempre di creare un clima sereno. Talvolta rischi di essere sottovalutato, ma quando impari a dire “no” con dolcezza, la tua voce acquista grande forza.',
                'metadata'          => json_encode(['keywords' => ['delicatezza', 'mediazione', 'empatia visibile']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'personality',
                'number_value'      => 3,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 3 – Presenza solare',
                'short_description' => 'Appari comunicativo, brillante, socievole.',
                'long_description'  => 'Con una personalità 3, gli altri ti vedono come persona vivace, simpatica e portata alla battuta. Spesso diventi il centro della conversazione, anche senza volerlo. Dietro il sorriso può esserci una grande sensibilità: quando impari a mostrarti anche nei momenti di fragilità, le tue relazioni diventano più vere.',
                'metadata'          => json_encode(['keywords' => ['solarità', 'simpatia', 'comunicatività esterna']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'personality',
                'number_value'      => 4,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 4 – Presenza solida',
                'short_description' => 'Appari affidabile, ordinato e concreto.',
                'long_description'  => 'La personalità 4 ti fa percepire come persona seria, organizzata e pratica. Gli altri si affidano a te perché sembri stabile e coerente. A volte però puoi risultare rigido o poco flessibile. Quando lasci vedere anche la tua parte più morbida, le persone si avvicinano a te con ancora più fiducia.',
                'metadata'          => json_encode(['keywords' => ['solidità', 'ordine', 'affidabilità visibile']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'personality',
                'number_value'      => 5,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 5 – Presenza dinamica',
                'short_description' => 'Appari vivace, curioso e imprevedibile.',
                'long_description'  => 'Con una personalità 5, dagli altri vieni visto come spirito libero, amante delle novità e del movimento. La gente percepisce in te spontaneità e voglia di vivere. Tuttavia qualcuno può leggerti come incostante. Quando trovi un minimo di continuità nei tuoi impegni, la tua energia contagiosa diventa un grande valore.',
                'metadata'          => json_encode(['keywords' => ['dinamismo', 'curiosità', 'imprevedibilità']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'personality',
                'number_value'      => 6,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 6 – Presenza accogliente',
                'short_description' => 'Appari protettivo, affettuoso, orientato alla cura.',
                'long_description'  => 'La personalità 6 ti dona un’aura di calore e disponibilità. Gli altri ti cercano per un consiglio, un conforto, una parola buona. Puoi apparire come “chi si occupa di tutti”, rischiando di dimenticarti di te stesso. Quando impari a mettere confini sani, il tuo amore diventa ancora più puro e rispettato.',
                'metadata'          => json_encode(['keywords' => ['accoglienza', 'protezione', 'dolcezza esterna']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'personality',
                'number_value'      => 7,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 7 – Presenza misteriosa',
                'short_description' => 'Appari riservato, introspettivo, profondo.',
                'long_description'  => 'Con una personalità 7, sei percepito come persona silenziosa, osservatrice, forse un po’ distante. Gli altri intuiscono che dentro di te c’è un mondo ricco, anche se non sempre lo condividi. Quando impari a rivelare gradualmente i tuoi pensieri e sentimenti, diventi un riferimento stabile e saggio.',
                'metadata'          => json_encode(['keywords' => ['mistero', 'profondità', 'riservatezza']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'personality',
                'number_value'      => 8,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 8 – Presenza autorevole',
                'short_description' => 'Appari forte, deciso, con energia di comando.',
                'long_description'  => 'La personalità 8 fa sì che gli altri ti percepiscano come figura autorevole, intraprendente, capace di prendere in mano la situazione. Alcuni possono temerti o sentirti distante. Quando mostri anche umanità e ascolto, la tua autorevolezza si trasforma in vera guida.',
                'metadata'          => json_encode(['keywords' => ['autorità', 'forza', 'impatto esterno']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'personality',
                'number_value'      => 9,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 9 – Presenza empatica',
                'short_description' => 'Appari sensibile, profondo e disponibile all’ascolto.',
                'long_description'  => 'Con una personalità 9, gli altri ti vedono come persona empatica, comprensiva e talvolta un po’ malinconica. Attiri confidenze e storie difficili, perché emani fiducia e compassione. La sfida è non assorbire il dolore altrui fino a dimenticare il tuo. Quando trovi equilibrio, diventi un consolatore naturale.',
                'metadata'          => json_encode(['keywords' => ['empatia', 'profondità emotiva', 'ascolto']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- PERSONALITY 11-22-33 (numeri maestri - immagine esterna) ---------- //
            [
                'number_type'       => 'personality',
                'number_value'      => 11,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 11 - Presenza ispirante',
                'short_description' => 'Appari sensibile, intuitivo e portatore di visione.',
                'long_description'  => 'Con una personalità 11, gli altri ti percepiscono come una persona fuori dal comune: ispirata, profonda, talvolta enigmatica. Trasmetti intuizione, idealismo e una certa tensione verso l’alto. Puoi sembrare fragile o nervoso, perché vivi su frequenze sottili. Quando impari a restare centrato, la tua presenza diventa una guida silenziosa per chi ti incontra.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'presenza ispirante',
                        'sensibilità elevata',
                        'intuizione visibile',
                        'carisma sottile',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'personality',
                'number_value'      => 22,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 22 - Presenza autorevole e solida',
                'short_description' => 'Appari affidabile, capace di guidare e costruire.',
                'long_description'  => 'La personalità 22 ti rende visibile come persona competente, concreta e orientata ai risultati. Gli altri sentono che possono contare su di te per realizzare qualcosa di importante. Trasmetti forza, stabilità e visione pratica. Il rischio è apparire distante o troppo focalizzato sugli obiettivi. Quando mostri anche il cuore, la tua autorevolezza diventa ispirazione.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'autorevolezza',
                        'solidità',
                        'leadership concreta',
                        'presenza strutturata',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'personality',
                'number_value'      => 33,
                'locale'            => 'it-IT',
                'title'             => 'Personalità 33 - Presenza compassionevole',
                'short_description' => 'Appari accogliente, amorevole e profondamente empatico.',
                'long_description'  => 'Con una personalità 33, gli altri ti vedono come figura di conforto, guida affettiva o riferimento morale. Emani comprensione, disponibilità e desiderio di aiutare. Spesso attrai confidenze e bisogni profondi. La sfida è non caricarti di tutto. Quando impari a mantenere confini sani, la tua compassione diventa una forza luminosa.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'compassione',
                        'empatia visibile',
                        'cura',
                        'presenza amorevole',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- BIRTH DAY 1–9 (giorno di nascita ridotto) ---------- //
            [
                'number_type'       => 'birth_day',
                'number_value'      => 1,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 1',
                'short_description' => 'Indica iniziativa naturale e voglia di affermarti.',
                'long_description'  => 'Nascere il giorno 1 (o ridotto a 1) porta una vibrazione di individualità e coraggio. Spontaneamente tendi a prendere l’iniziativa, a proporre, a guidare. Fin da giovane potresti aver sentito il bisogno di dimostrare il tuo valore senza dipendere dagli altri.',
                'metadata'          => json_encode(['keywords' => ['iniziativa', 'affermazione', 'indipendenza precoce']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'birth_day',
                'number_value'      => 2,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 2',
                'short_description' => 'Indica sensibilità precoce e forte bisogno di legame.',
                'long_description'  => 'Nascere il giorno 2 (o ridotto a 2) porta una nota di delicatezza, empatia e cooperazione. Da bambino potresti aver cercato armonia e protezione, avendo un forte radar emotivo verso l’ambiente familiare.',
                'metadata'          => json_encode(['keywords' => ['sensibilità', 'legame', 'cooperazione precoce']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'birth_day',
                'number_value'      => 3,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 3',
                'short_description' => 'Porta spontaneità, gioco e bisogno di esprimerti.',
                'long_description'  => 'Il giorno 3 rende naturale la tendenza a ridere, scherzare, raccontare e attirare attenzione con la parola. Da giovane la creatività può mostrarsi in molti modi: disegno, musica, scrittura, teatro.',
                'metadata'          => json_encode(['keywords' => ['gioco', 'espressione', 'spontaneità']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'birth_day',
                'number_value'      => 4,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 4',
                'short_description' => 'Porta senso pratico, ordine e attenzione alle regole.',
                'long_description'  => 'Il giorno 4 dona un approccio ordinato e concreto alla vita. Fin da piccolo potresti aver sentito il bisogno di routine, chiarezza e stabilità, con una naturale avversione al caos.',
                'metadata'          => json_encode(['keywords' => ['ordine', 'pragmatismo', 'regole']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'birth_day',
                'number_value'      => 5,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 5',
                'short_description' => 'Porta curiosità, movimento e cambiamenti frequenti.',
                'long_description'  => 'Il giorno 5 indica una personalità vivace, attratta dal nuovo e dalle esperienze forti. Spesso la vita ti mette presto davanti a cambiamenti, spostamenti o situazioni non convenzionali.',
                'metadata'          => json_encode(['keywords' => ['curiosità', 'cambiamento', 'movimento precoce']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'birth_day',
                'number_value'      => 6,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 6',
                'short_description' => 'Porta senso di responsabilità affettiva e amore per l’armonia.',
                'long_description'  => 'Il giorno 6 porta una naturale inclinazione a prenderti cura degli altri e dell’ambiente. Da giovane potresti essere stato il “pacificatore” o il punto fermo della famiglia, anche quando eri ancora bambino.',
                'metadata'          => json_encode(['keywords' => ['responsabilità', 'armonia', 'cura precoce']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'birth_day',
                'number_value'      => 7,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 7',
                'short_description' => 'Porta introspezione, osservazione e ricerca interiore.',
                'long_description'  => 'Il giorno 7 suggerisce un temperamento attento, contemplativo, talvolta riservato. Fin da giovane puoi aver sentito il bisogno di capire il “perché” delle cose, più che di seguirle ciecamente.',
                'metadata'          => json_encode(['keywords' => ['introspezione', 'osservazione', 'ricerca interiore precoce']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'birth_day',
                'number_value'      => 8,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 8',
                'short_description' => 'Porta ambizione naturale e coscienza del potere personale.',
                'long_description'  => 'Il giorno 8 indica una spinta verso obiettivi importanti, il desiderio di contare e di avere un impatto. Fin da giovane puoi aver sperimentato temi di responsabilità, giustizia, merito.',
                'metadata'          => json_encode(['keywords' => ['ambizione', 'potere', 'giustizia precoce']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'birth_day',
                'number_value'      => 9,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 9',
                'short_description' => 'Porta sensibilità, empatia e intuizione profonda.',
                'long_description'  => 'Il giorno 9 suggerisce un cuore attento agli altri, sensibile alle ingiustizie e alle emozioni collettive. Fin dall’infanzia potresti averti sentito diverso, più maturo o più emotivo rispetto ai tuoi coetanei.',
                'metadata'          => json_encode(['keywords' => ['sensibilità', 'empatia', 'intuizione precoce']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- BIRTH DAY 11-22 (numeri maestri - giorno di nascita ridotto) ---------- //
            [
                'number_type'       => 'birth_day',
                'number_value'      => 11,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 11',
                'short_description' => 'Indica sensibilità intuitiva e percezione fuori dal comune.',
                'long_description'  => 'Nascere l’11 porta fin dall’infanzia una vibrazione intensa e sottile. Puoi aver mostrato grande sensibilità, intuizione o immaginazione, ma anche nervosismo o senso di diversità. Questo numero parla di una predisposizione naturale a percepire ciò che non è immediatamente visibile. Crescendo, impari a trasformare questa sensibilità in dono.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'sensibilità precoce',
                        'intuizione',
                        'percezione sottile',
                        'nascita speciale',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'birth_day',
                'number_value'      => 22,
                'locale'            => 'it-IT',
                'title'             => 'Giorno di nascita 22',
                'short_description' => 'Indica maturità precoce e senso innato di responsabilità.',
                'long_description'  => 'Nascere il giorno 22 suggerisce una predisposizione naturale a prendere sul serio la realtà fin da giovane. Puoi aver sentito presto il peso delle responsabilità o il bisogno di costruire qualcosa di stabile. Questo giorno porta una forza concreta, spesso accompagnata da grandi aspettative. La crescita consiste nel non irrigidirsi troppo presto, lasciando spazio anche al gioco.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'responsabilità precoce',
                        'solidità',
                        'forza concreta',
                        'maturità anticipata',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- MATURITY 1–9 (sintesi evolutiva) ---------- //
            [
                'number_type'       => 'maturity',
                'number_value'      => 1,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 1 – Il nuovo inizio permanente',
                'short_description' => 'La vita ti porta a diventare sempre più autonomo e guida.',
                'long_description'  => 'Con una maturità 1, gli anni avanzano spingendoti verso la piena affermazione del tuo sé. È come se la vita, col tempo, ti mettesse sempre più spesso in prima linea. Sei chiamato a decidere con coraggio, a creare progetti tuoi, a non nasconderti dietro gli altri.',
                'metadata'          => json_encode(['keywords' => ['autonomia evolutiva', 'leadership matura']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'maturity',
                'number_value'      => 2,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 2 – La saggezza della relazione',
                'short_description' => 'La vita ti porta verso collaborazione, ascolto e unione.',
                'long_description'  => 'Con una maturità 2, più il tempo passa, più diventa centrale la qualità delle tue relazioni. Impari l’arte della pazienza, dell’ascolto, della scelta consapevole dei tuoi legami. È un cammino che ti porta dal bisogno di essere visto al piacere di condividere.',
                'metadata'          => json_encode(['keywords' => ['relazione matura', 'collaborazione evolutiva']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'maturity',
                'number_value'      => 3,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 3 – La parola al servizio del cuore',
                'short_description' => 'La vita ti porta a esprimerti in modo sempre più autentico.',
                'long_description'  => 'Con maturità 3, gli anni ti guidano a usare la comunicazione non solo per brillare, ma per guarire te stesso e gli altri. Scopri che ogni parola può essere preghiera, arte o cura. Crescere significa imparare a dire la verità con dolcezza e creatività.',
                'metadata'          => json_encode(['keywords' => ['espressione matura', 'comunicazione consapevole']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'maturity',
                'number_value'      => 4,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 4 – La costruzione paziente',
                'short_description' => 'La vita ti porta a consolidare, strutturare, rendere stabile.',
                'long_description'  => 'Con maturità 4, col passare degli anni aumenta il bisogno di vedere risultati concreti e duraturi. Impari l’arte della perseveranza e della responsabilità, ma sei chiamato anche a non indurirti. Maturare significa creare fondamenta solide, restando aperto al soffio dello Spirito.',
                'metadata'          => json_encode(['keywords' => ['struttura evolutiva', 'perseveranza matura']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'maturity',
                'number_value'      => 5,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 5 – La libertà consapevole',
                'short_description' => 'La vita ti porta a integrare cambiamento e responsabilità.',
                'long_description'  => 'Con maturità 5, la seconda parte della vita porta spesso cambiamenti importanti: di lavoro, di luogo, di relazioni. Sei chiamato a vivere la libertà non come fuga, ma come scelta consapevole. La vera maturità qui è dire “sì” solo a ciò che ti rende veramente più integro.',
                'metadata'          => json_encode(['keywords' => ['libertà matura', 'cambiamento consapevole']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'maturity',
                'number_value'      => 6,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 6 – La responsabilità del cuore',
                'short_description' => 'La vita ti porta verso cura, famiglia, amore responsabile.',
                'long_description'  => 'Con maturità 6, col tempo diventa centrale la qualità dell’amore che dai e che ricevi. Puoi trovarti a gestire responsabilità familiari, educative o di cura. La lezione è imparare a scegliere a chi e a che cosa donare le tue energie, senza cadere nel martirio.',
                'metadata'          => json_encode(['keywords' => ['amore maturo', 'responsabilità affettiva evolutiva']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'maturity',
                'number_value'      => 7,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 7 – La contemplazione profonda',
                'short_description' => 'La vita ti porta verso introspezione e ricerca spirituale.',
                'long_description'  => 'Con maturità 7, gli anni intensificano il richiamo alla verità interiore. Puoi sentire il bisogno di ritirarti, studiare, pregare, comprendere. Maturare significa smettere di fuggire dal silenzio e scoprire che lì non sei solo, ma accompagnato.',
                'metadata'          => json_encode(['keywords' => ['ricerca matura', 'spiritualità evolutiva']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'maturity',
                'number_value'      => 8,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 8 – Il potere responsabile',
                'short_description' => 'La vita ti porta a confrontarti col potere e con l’etica.',
                'long_description'  => 'Con maturità 8, la seconda parte della vita mette in primo piano temi di successo, denaro, autorità. La sfida è usare queste energie in modo giusto. La vera maturità è capire che il potere autentico è servizio e che la prosperità è un flusso da gestire con coscienza.',
                'metadata'          => json_encode(['keywords' => ['potere maturo', 'etica del successo']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'maturity',
                'number_value'      => 9,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 9 – Il compimento',
                'short_description' => 'La vita ti porta a chiudere cicli e donare saggezza.',
                'long_description'  => 'Con maturità 9, gli anni ti invitano a rivedere il passato, a perdonare e a donare. Spesso comporta grandi chiusure o distacchi, che però aprono a una nuova forma di amore universale. La tua saggezza diventa dono per chi viene dopo di te.',
                'metadata'          => json_encode(['keywords' => ['compimento', 'saggezza matura', 'chiusura di cicli']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- MATURITY 11–22-33 (numeri maestri) ---------- //
            [
                'number_type'       => 'maturity',
                'number_value'      => 11,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 11 – Il Faro spirituale',
                'short_description' => 'La vita ti conduce a ispirare, illuminare e guidare con coscienza.',
                'long_description'  => 'Con una maturità 11, la seconda parte della vita assume una forte dimensione spirituale e simbolica. Sei chiamato a diventare canale di ispirazione, verità e visione per gli altri. Non si tratta di potere personale, ma di responsabilità luminosa: ciò che vivi, comprendi e superi diventa luce per chi cammina accanto a te. La sfida è restare radicato, per non disperdere l’energia in idealismo o tensione nervosa.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'ispirazione',
                        'guida spirituale',
                        'coscienza elevata',
                        'luce per gli altri',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'maturity',
                'number_value'      => 22,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 22 – Il Grande Costruttore',
                'short_description' => 'La vita ti porta a realizzare opere durature al servizio del collettivo.',
                'long_description'  => 'Con una maturità 22, la seconda parte della vita unisce visione spirituale e capacità concreta. Sei chiamato a costruire qualcosa che resti: strutture, progetti, opere, comunità. Non basta sognare, devi incarnare. La sfida è non schiacciare l’anima sotto il peso della responsabilità. Quando unisci spirito e materia, diventi architetto del bene comune.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'grande costruttore',
                        'realizzazione collettiva',
                        'visione incarnata',
                        'responsabilità spirituale',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'maturity',
                'number_value'      => 33,
                'locale'            => 'it-IT',
                'title'             => 'Maturità 33 – Il Maestro compassionevole',
                'short_description' => 'La vita ti conduce a servire attraverso amore, guida e guarigione.',
                'long_description'  => 'Con una maturità 33, la maturazione dell’anima ti porta verso il servizio totale. È il numero dell’amore universale incarnato: insegnare, guarire, sostenere, elevare. La sfida è non sacrificarti fino all’annullamento. La vera maestria è amare senza perdere te stesso, diventando presenza che cura semplicemente esistendo.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'maestro spirituale',
                        'amore universale',
                        'servizio compassionevole',
                        'guarigione collettiva',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- BALANCE 1–9 (reazioni sotto stress) ---------- //
            [
                'number_type'       => 'balance',
                'number_value'      => 1,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 1 – Reazione attiva',
                'short_description' => 'Sotto pressione tendi a reagire prendendo il comando.',
                'long_description'  => 'Con numero di equilibrio 1, nei momenti difficili scatta in te l’istinto di “fare qualcosa subito”. Puoi diventare più diretto, deciso, talvolta brusco. Il rimedio è fermarti un attimo prima di agire, così la tua energia di iniziativa diventa guida e non impulsività.',
                'metadata'          => json_encode(['keywords' => ['reazione attiva', 'azione immediata', 'assertività sotto stress']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'balance',
                'number_value'      => 2,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 2 – Reazione sensibile',
                'short_description' => 'Sotto pressione ti chiudi, osservi e cerchi armonia.',
                'long_description'  => 'Con equilibrio 2, nelle crisi puoi diventare più silenzioso, iper-sensibile e attento alle reazioni altrui. Il rischio è evitare il confronto. L’equilibrio arriva quando impari a dire con dolcezza ciò che provi, invece di fuggire il conflitto.',
                'metadata'          => json_encode(['keywords' => ['reazione sensibile', 'evitamento del conflitto', 'mediazione sotto stress']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'balance',
                'number_value'      => 3,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 3 – Reazione espressiva',
                'short_description' => 'Sotto pressione parli, sfoghi, cerchi di alleggerire.',
                'long_description'  => 'Con equilibrio 3, tendi a reagire parlando molto, scherzando o raccontando ciò che accade. È il tuo modo di non affogare nell’emozione. L’equilibrio arriva quando impari anche ad ascoltare il silenzio tra una parola e l’altra.',
                'metadata'          => json_encode(['keywords' => ['sfogo verbale', 'ironia', 'bisogno di comunicare sotto stress']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'balance',
                'number_value'      => 4,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 4 – Reazione strutturante',
                'short_description' => 'Sotto pressione ti aggrappi a routine e regole.',
                'long_description'  => 'Con equilibrio 4, quando le cose si complicano cerchi subito di rimettere ordine, fare liste, creare nuove strutture. Questo è un grande dono, ma può diventare rigidità. Quando lasci un piccolo spazio all’imprevisto, la tua organizzazione diventa ancora più efficace.',
                'metadata'          => json_encode(['keywords' => ['ordine sotto stress', 'rigidità', 'strutturazione']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'balance',
                'number_value'      => 5,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 5 – Reazione di fuga o cambiamento',
                'short_description' => 'Sotto pressione vuoi cambiare aria, situazione, contesto.',
                'long_description'  => 'Con equilibrio 5, nelle difficoltà la prima spinta può essere quella di scappare, cambiare tutto, rompere schemi. A volte è necessario, ma altre volte è solo fuga. L’equilibrio viene quando distingui tra cambiamento liberatorio e cambiamento impulsivo.',
                'metadata'          => json_encode(['keywords' => ['fuga', 'cambiamento improvviso', 'spinta alla libertà sotto stress']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'balance',
                'number_value'      => 6,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 6 – Reazione protettiva',
                'short_description' => 'Sotto pressione cerchi di proteggere chi ami, anche a costo di sovraccaricarti.',
                'long_description'  => 'Con equilibrio 6, nei momenti complessi ti fai carico dei problemi, spesso di tutti. Vuoi sistemare, pacificare, rassicurare. Se non ti proteggi, rischi l’esaurimento emotivo. L’equilibrio sta nel condividere i pesi e chiedere aiuto.',
                'metadata'          => json_encode(['keywords' => ['iper-responsabilità', 'protezione', 'sovraccarico affettivo']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'balance',
                'number_value'      => 7,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 7 – Reazione di ritiro',
                'short_description' => 'Sotto pressione ti isoli e cerchi risposte dentro.',
                'long_description'  => 'Con equilibrio 7, nelle crisi hai bisogno di silenzio, distanza e tempo per elaborare. È una risorsa preziosa, ma può diventare chiusura totale. Quando impari a condividere almeno una parte di ciò che vivi, la tua introspezione diventa un grande punto di forza.',
                'metadata'          => json_encode(['keywords' => ['ritiro', 'isolamento', 'ricerca interiore sotto stress']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'balance',
                'number_value'      => 8,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 8 – Reazione autoritaria',
                'short_description' => 'Sotto pressione puoi irrigidirti su controllo e risultati.',
                'long_description'  => 'Con equilibrio 8, nelle situazioni critiche puoi diventare più duro, esigente, focalizzato su ciò che va fatto ad ogni costo. Questo porta efficienza, ma può ferire gli altri. L’equilibrio nasce quando ricordi che le persone valgono più dei risultati.',
                'metadata'          => json_encode(['keywords' => ['controllo', 'autorità', 'pressione sui risultati']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'balance',
                'number_value'      => 9,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 9 – Reazione emotiva profonda',
                'short_description' => 'Sotto pressione senti tutto molto intensamente.',
                'long_description'  => 'Con equilibrio 9, nelle crisi puoi esplodere in forti emozioni o chiuderti in un silenzio carico. Assorbi non solo il tuo dolore, ma anche quello degli altri. L’equilibrio arriva quando impari a lasciar fluire ciò che senti, senza identificarti totalmente con la sofferenza.',
                'metadata'          => json_encode(['keywords' => ['intensità emotiva', 'empatia sotto stress', 'rilascio emotivo']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- BALANCE 11–22-33 (numeri maestri - reazioni sotto stress) ---------- //
            [
                'number_type'       => 'balance',
                'number_value'      => 11,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 11 - Reazione ipersensibile e intuitiva',
                'short_description' => 'Sotto pressione reagisci amplificando percezioni ed emozioni.',
                'long_description'  => 'Con un equilibrio 11, nei momenti di stress diventi estremamente ricettivo: percepisci tutto, anche ciò che gli altri non notano. Questo può portare ispirazione improvvisa, ma anche sovraccarico emotivo o nervoso. L’equilibrio si ritrova quando impari a radicarti, distinguendo ciò che è tuo da ciò che assorbi dall’ambiente.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'ipersensibilità',
                        'intuizione sotto stress',
                        'sovraccarico emotivo',
                        'radicamento',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'balance',
                'number_value'      => 22,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 22 - Reazione di controllo e strutturazione',
                'short_description' => 'Sotto pressione cerchi di reggere tutto e rimettere ordine.',
                'long_description'  => 'Con equilibrio 22, nelle situazioni critiche senti il bisogno di assumerti responsabilità e tenere insieme la struttura. Reagisci costruendo, organizzando e controllando per evitare il collasso. È una grande forza, ma può trasformarsi in rigidità. L’equilibrio arriva quando condividi il peso e accetti che non tutto dipende da te.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'controllo',
                        'responsabilità',
                        'strutturazione',
                        'tenuta sotto stress',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'balance',
                'number_value'      => 33,
                'locale'            => 'it-IT',
                'title'             => 'Equilibrio 33 - Reazione di sacrificio e cura',
                'short_description' => 'Sotto pressione tendi a prenderti cura di tutti, anche a tuo costo.',
                'long_description'  => 'Con equilibrio 33, nelle difficoltà la tua prima risposta è aiutare, sostenere, farti carico del dolore altrui. È una reazione profondamente amorevole, ma rischiosa. L’equilibrio nasce quando impari che prenderti cura di te non è egoismo, ma condizione per continuare a servire con verità.',
                'metadata'          => json_encode([
                    'keywords' => [
                        'numero maestro',
                        'sacrificio',
                        'cura',
                        'servizio sotto stress',
                        'confini sani',
                    ],
                ]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- KARMIC LESSON 1–9 ---------- //
            [
                'number_type'       => 'karmic_lesson',
                'number_value'      => 1,
                'locale'            => 'it-IT',
                'title'             => 'Lezione karmica 1 – Imparare ad affermarsi',
                'short_description' => 'Mancanza di 1 nel nome: tema dell’autostima e dell’iniziativa personale.',
                'long_description'  => 'La lezione karmica 1 indica che in questa vita sei chiamato a sviluppare coraggio, iniziativa e fiducia in te stesso. Puoi avere paura di prendere decisioni o di metterti al centro. Ogni volta che scegli di affermare con rispetto la tua verità, stai guarendo questa lezione.',
                'metadata'          => json_encode(['keywords' => ['autostima', 'iniziativa', 'coraggio karmico']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'karmic_lesson',
                'number_value'      => 2,
                'locale'            => 'it-IT',
                'title'             => 'Lezione karmica 2 – Imparare a collaborare',
                'short_description' => 'Mancanza di 2 nel nome: tema della cooperazione e della sensibilità.',
                'long_description'  => 'La lezione karmica 2 parla di rispetto dei tempi altrui, ascolto e relazione. Potresti oscillare tra eccesso di indipendenza e bisogno di fusione. Imparare a cooperare senza perdere te stesso è il nucleo di questa guarigione.',
                'metadata'          => json_encode(['keywords' => ['cooperazione', 'ascolto', 'relazione karmica']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'karmic_lesson',
                'number_value'      => 3,
                'locale'            => 'it-IT',
                'title'             => 'Lezione karmica 3 – Imparare a esprimersi',
                'short_description' => 'Mancanza di 3 nel nome: tema della comunicazione e della gioia.',
                'long_description'  => 'La lezione karmica 3 ti invita a dare voce a ciò che senti e pensi. Puoi aver vissuto blocchi espressivi, derisione o non ascolto. Il lavoro karmico è ritrovare la gioia, l’umorismo sano e la capacità di raccontare la tua storia.',
                'metadata'          => json_encode(['keywords' => ['espressione', 'gioia', 'voce karmica']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'karmic_lesson',
                'number_value'      => 4,
                'locale'            => 'it-IT',
                'title'             => 'Lezione karmica 4 – Imparare la disciplina',
                'short_description' => 'Mancanza di 4 nel nome: tema dell’ordine e della perseveranza.',
                'long_description'  => 'La lezione karmica 4 porta sfide legate alla costanza, alla gestione pratica della vita, al rispetto dei limiti. Puoi sentirti facilmente sopraffatto dalle responsabilità. Ogni piccolo passo di organizzazione e concretezza è un atto di guarigione karmica.',
                'metadata'          => json_encode(['keywords' => ['disciplina', 'ordine', 'responsabilità karmica']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'karmic_lesson',
                'number_value'      => 5,
                'locale'            => 'it-IT',
                'title'             => 'Lezione karmica 5 – Imparare la vera libertà',
                'short_description' => 'Mancanza di 5 nel nome: tema del cambiamento e della flessibilità.',
                'long_description'  => 'La lezione karmica 5 indica che devi imparare a vivere il cambiamento senza paura né eccessi. Può esserci tendenza al controllo o, al contrario, alla fuga improvvisa. La guarigione è scegliere il nuovo in modo consapevole, non per ribellione cieca.',
                'metadata'          => json_encode(['keywords' => ['libertà', 'cambiamento', 'flessibilità karmica']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'karmic_lesson',
                'number_value'      => 6,
                'locale'            => 'it-IT',
                'title'             => 'Lezione karmica 6 – Imparare l’amore equilibrato',
                'short_description' => 'Mancanza di 6 nel nome: tema della cura e della responsabilità affettiva.',
                'long_description'  => 'La lezione karmica 6 parla di famiglia, impegni affettivi e cura degli altri. Puoi avere difficoltà a prenderti responsabilità in amore o, al contrario, sentirti intrappolato nei doveri. Lavorare su confini sani e scelta del cuore è fondamentale.',
                'metadata'          => json_encode(['keywords' => ['amore', 'famiglia', 'responsabilità karmica affettiva']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'karmic_lesson',
                'number_value'      => 7,
                'locale'            => 'it-IT',
                'title'             => 'Lezione karmica 7 – Imparare la fiducia spirituale',
                'short_description' => 'Mancanza di 7 nel nome: tema della fede, della fiducia e della profondità.',
                'long_description'  => 'La lezione karmica 7 indica difficoltà con la fede, il dubbio, la diffidenza. Potresti avere paura di fidarti o di seguire il tuo intuito. Il lavoro è recuperare un rapporto vivo con il Mistero, imparando a non basarti solo sulla logica.',
                'metadata'          => json_encode(['keywords' => ['fede', 'intuizione', 'profondità karmica']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'karmic_lesson',
                'number_value'      => 8,
                'locale'            => 'it-IT',
                'title'             => 'Lezione karmica 8 – Imparare il giusto uso del potere',
                'short_description' => 'Mancanza di 8 nel nome: tema del denaro, del successo e dell’autorità.',
                'long_description'  => 'La lezione karmica 8 porta prove legate a lavoro, denaro, riconoscimento e giustizia. Puoi vivere alti e bassi forti in questi ambiti. La guarigione consiste nel sviluppare un rapporto sano con il valore, tuo e delle cose.',
                'metadata'          => json_encode(['keywords' => ['potere', 'denaro', 'giustizia karmica']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'karmic_lesson',
                'number_value'      => 9,
                'locale'            => 'it-IT',
                'title'             => 'Lezione karmica 9 – Imparare a lasciare andare',
                'short_description' => 'Mancanza di 9 nel nome: tema del perdono e delle chiusure.',
                'long_description'  => 'La lezione karmica 9 riguarda la difficoltà a chiudere, perdonare e lasciar andare ciò che non serve più. Puoi rimanere attaccato a rapporti, situazioni o ruoli ormai finiti. Ogni atto di perdono e rilascio consapevole scioglie nodi antichi.',
                'metadata'          => json_encode(['keywords' => ['perdono', 'distacco', 'chiusura karmica']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ---------- HIDDEN PASSION 1–9 ---------- //
            [
                'number_type'       => 'hidden_passion',
                'number_value'      => 1,
                'locale'            => 'it-IT',
                'title'             => 'Passione nascosta 1 – Voler guidare',
                'short_description' => 'Dentro di te c’è un forte impulso a essere il primo.',
                'long_description'  => 'La passione nascosta 1 indica un desiderio intenso di guidare, dimostrare il tuo valore, affermare la tua individualità. Anche se in superficie puoi sembrare tranquillo, dentro vuoi creare qualcosa di tuo, unico.',
                'metadata'          => json_encode(['keywords' => ['leadership interiore', 'affermazione nascosta']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'hidden_passion',
                'number_value'      => 2,
                'locale'            => 'it-IT',
                'title'             => 'Passione nascosta 2 – Voler unire',
                'short_description' => 'Dentro di te c’è un forte desiderio di creare legami profondi.',
                'long_description'  => 'La passione nascosta 2 parla di un bisogno intimo di collaborazione, comprensione e delicatezza. Anche se esteriormente puoi mostrarti forte o distaccato, dentro sogni unioni sincere e non conflittuali.',
                'metadata'          => json_encode(['keywords' => ['unione nascosta', 'bisogno di relazione profonda']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'hidden_passion',
                'number_value'      => 3,
                'locale'            => 'it-IT',
                'title'             => 'Passione nascosta 3 – Voler creare',
                'short_description' => 'Dentro di te c’è un forte desiderio di esprimerti artisticamente.',
                'long_description'  => 'La passione nascosta 3 indica un fuoco creativo che forse non mostri apertamente. Puoi avere talento per scrittura, musica, disegno, ma tenerlo nell’ombra. Quando lo lasci emergere, molta energia bloccata riprende a fluire.',
                'metadata'          => json_encode(['keywords' => ['creatività nascosta', 'espressione artistica interiore']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'hidden_passion',
                'number_value'      => 4,
                'locale'            => 'it-IT',
                'title'             => 'Passione nascosta 4 – Voler stabilità',
                'short_description' => 'Dentro di te c’è un forte desiderio di avere basi sicure.',
                'long_description'  => 'La passione nascosta 4 suggerisce che, al di là dell’immagine esterna, desideri profondamente ordine, metodo e sicurezza concreta. Puoi lavorare duramente in silenzio per costruire stabilità tua e di chi ami.',
                'metadata'          => json_encode(['keywords' => ['stabilità nascosta', 'ordine interiore']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'hidden_passion',
                'number_value'      => 5,
                'locale'            => 'it-IT',
                'title'             => 'Passione nascosta 5 – Voler esplorare',
                'short_description' => 'Dentro di te c’è un forte desiderio di viaggiare e sperimentare.',
                'long_description'  => 'La passione nascosta 5 mostra un bisogno interiore di libertà, di esperienze diverse, di contatti con persone e luoghi nuovi. Anche se la tua vita appare stabile, dentro sogni cambiamenti e orizzonti più ampi.',
                'metadata'          => json_encode(['keywords' => ['esplorazione nascosta', 'sete di libertà interiore']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'hidden_passion',
                'number_value'      => 6,
                'locale'            => 'it-IT',
                'title'             => 'Passione nascosta 6 – Voler amare e proteggere',
                'short_description' => 'Dentro di te c’è un forte desiderio di creare un nido affettivo.',
                'long_description'  => 'La passione nascosta 6 indica che, anche se non lo mostri apertamente, sogni relazioni stabili, famiglia, bellezza, armonia domestica. Quando inizi a permetterti questa dimensione, una parte profonda di te respira.',
                'metadata'          => json_encode(['keywords' => ['amore nascosto', 'bisogno di casa e famiglia']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'hidden_passion',
                'number_value'      => 7,
                'locale'            => 'it-IT',
                'title'             => 'Passione nascosta 7 – Voler capire il mistero',
                'short_description' => 'Dentro di te c’è un forte desiderio di conoscenza interiore.',
                'long_description'  => 'La passione nascosta 7 parla di una sete segreta di verità, spiritualità, contemplazione. Puoi vivere esteriormente in modo pratico, ma dentro cerchi risposte profonde e autentiche sulla vita e su Dio.',
                'metadata'          => json_encode(['keywords' => ['ricerca nascosta', 'sete spirituale interiore']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'hidden_passion',
                'number_value'      => 8,
                'locale'            => 'it-IT',
                'title'             => 'Passione nascosta 8 – Voler realizzare in grande',
                'short_description' => 'Dentro di te c’è un forte desiderio di successo e impatto.',
                'long_description'  => 'La passione nascosta 8 indica che, anche se non lo dichiari, desideri avere peso nel mondo, gestire risorse, vincere sfide importanti. Quando integri questa energia con etica e cuore, puoi manifestare risultati importanti.',
                'metadata'          => json_encode(['keywords' => ['successo nascosto', 'impatto interiore']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'number_type'       => 'hidden_passion',
                'number_value'      => 9,
                'locale'            => 'it-IT',
                'title'             => 'Passione nascosta 9 – Voler guarire il mondo',
                'short_description' => 'Dentro di te c’è un forte desiderio di aiutare e servire.',
                'long_description'  => 'La passione nascosta 9 parla di un grande desiderio interiore di portare sollievo, conforto, arte o presenza a chi soffre. Anche se la vita ti porta su altre strade, una parte di te sogna sempre di essere al servizio della guarigione collettiva.',
                'metadata'          => json_encode(['keywords' => ['servizio nascosto', 'vocazione umanitaria interiore']]),
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];

        DB::table('pythagoric_meanings')->insert($rows);
    }
}
